### ISSUE TITLE
Better abstraction of policy runtimes

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-evaluator#24]
Right now policy-evaluator has to runtimes: waPC (the original one) and burrego (the one that handles OPA and Gatekeeper policies).

The current codebase deals with that by using some `match` statements (basically Rust equivalent of a `switch`). This makes the code ugly and hard to maintain.

We can remove this complexity by using some Rust traits.

For more details about the pieces of the code that have to be updated, take a look at the comments against this PR: https://github.com/kubewarden/policy-evaluator/pull/22

**Comment by ereslibre** [comment]
Despite I'm misunderstanding I wouldn't do this at this time. Currently, we have a `Runtime` enum, and based on the variant, the `validate` or `validate_settings` on the `Runtime` type will behave differently.

This is not a case of different types having to implement a common interface. Please, tell me if I'm missing anything here.

**Comment by ereslibre** [comment]
Handled in https://github.com/kubewarden/policy-evaluator/pull/28
