### ISSUE TITLE
Rego: handle responses from OPA policy evaluation

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-evaluator#25]
The evaluation of a OPA policy returns a `AdmissionReview` object. The runtime should try to unmarshall the JSON object into that and, when error occur, return a rejection with error `code 500`.

**Comment by ereslibre** [comment]
I believe this is handled by https://github.com/kubewarden/policy-evaluator/blob/1e716aeb028678d31c93674140b1f0e925a67f3c/src/policy_evaluator.rs#L266-L323 already.

Let me know if you have something more in mind.

**Comment by ereslibre** [comment]
The `policy-evaluator` will always enforce the `uid` attribute on the result. After unmarshaling the result from OPA, it will always set the `uid` that corresponds to the request it is evaluating.

**Comment by ereslibre** [comment]
This is addressed. Implemented in https://github.com/kubewarden/policy-evaluator/pull/22.
