### ISSUE TITLE
tech debt: extend test suite to evaluate policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-evaluator#378]
Currently the test suite of policy-evaluator is not evaluating a policy. These tests are currently done inside of kwctl/policy-server e2e tests.
That means that, when breaking policy-evaluator, the bugs are noticed only later on inside of kwctl or policy-server.

It would be great to perform some real evaluations also inside of the tests of policy-evaluator, checking that the runtimes are working fine.

Note: I would prefer to NOT have to commit wasm modules to the git repository. I think we can leverage policy-fetcher to download the test policies and then evaluate them

**Comment by fabriziosestito** [comment]
Tests to add:
- [ ] Evaluate a OPA policy (simple, context-aware)
- [ ] Evaluate a Gatekeeper policy (simple, context-aware)
- [ ] Evaluate a WAPC policy (simple, context-aware)
- [ ] Evaluate a WASI policy

**Comment by flavio** [comment]
this is now done, can be closed
